name: 程序员小徐同学
#https://acolasia-xu.github.io/xudada/
#url: https://acolasia-xu.github.io/xudada/
#description: Insert tagline here

title:  程序员小徐体系
subtitle: 分享技术，品味人生
name: 程序员小徐体系 
email: 1375595011@qq.com
description: 本站是程序员小徐的技术分享博客。内容涵盖生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: xudada,程序员小徐体系,Spring,Spring Boot,Spring Cloud,MongoDB,Jvm,Docker,生活故事,架构,大数据,一线,FastDFS,开发者,编程,代码,开源,IT网站,Developer,Programmer,Coder,Geek,IT技术博客,Java,Python,
encoding: "utf-8"
favicon: favicon.ico 
# https://acolasia-xu.github.io/xudada.github.io/
github_url: https://github.com/acolasia-xu
url: https://acolasia-xu.github.io/xudada/
enforce_ssl: acolasia-xu.com



permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
